# Numpy Assignment

1. What is a Python library? Why do we use Python libraries?

Ans:

A Python library is a collection of pre-written code that you can use to perform common tasks without writing the code from scratch. Libraries often contain modules, classes, functions, and other resources that simplify and accelerate development in Python.

Why we use Python libraries:

Efficiency: Saves time by providing pre-built functionality.
Reusability: Code can be reused across different projects.
Reliability: Libraries are often well-tested and widely used, so they are likely to be more reliable than custom code.
Functionality: Provides tools for specific domains (e.g., NumPy for numerical computation, pandas for data analysis, etc.).

2. What is the difference between Numpy array and List?


Ans:

- Data Type: NumPy arrays are homogeneous, meaning all elements must be of the same data type. Python lists are heterogeneous, allowing elements of different data types.
- Performance: NumPy arrays are more memory-efficient and provide faster computations, particularly for large datasets, because they are implemented in C.
- Functionality: NumPy arrays support a wide range of mathematical operations (e.g., element-wise addition, multiplication) that are not natively supported by Python lists.
- Size: The size of a NumPy array is fixed, whereas Python lists are dynamic and can grow or shrink.

### 3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [2]:
import numpy as np

array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

shape = array.shape       
size = array.size         
dimension = array.ndim    

print(shape, size, dimension)


(3, 4) 12 2


### 4. Write python co^e to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [3]:
import numpy as np

array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
first_row = array[0]

first_row


array([1, 2, 3, 4])

5. How ^o you access the element at the thir^ row an^ fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [8]:
c

12

### 6. Write co^e to extract all o^^-in^exe^ elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [12]:
import numpy as np

array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
odd_indexed_elements = array[:, 1::2]

odd_indexed_elements

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

### 7. How can you generate a ran^om 3x3 matrix with values between 0 an^ 1?

In [13]:
import numpy as np

array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
random_matrix = np.random.rand(3, 3)

random_matrix

array([[0.8280406 , 0.34977037, 0.25206753],
       [0.14956349, 0.8007968 , 0.41394792],
       [0.5714448 , 0.28989297, 0.8537631 ]])

8. Describe the ^ifference between np.ran^om.ran^ an^ np.ran^om.ran^n?

- np.random.rand: Generates random numbers from a uniform distribution between 0 and 1.
- np.random.randn: Generates random numbers from a standard normal distribution (mean = 0, standard deviation = 1).

 ### 9. Write co^e to increase the ^imension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [14]:
import numpy as np

array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
array_3d = np.expand_dims(array, axis=0)

array_3d.shape



(1, 3, 4)

10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

11. Consi^er the following matrix:

Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

erform the following operation using Python1
,+ I(dex wiLe multiplicatio'
]+ Matix multiplicatio'
+ Add both the maticK
-+ Subtact matix B om 
+ Diide Matix B by A

In [16]:
# Matrix A2 and B2
A2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
B2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# 1. Element-wise multiplication
element_wise_multiplication = A2 * B2

# 2. Matrix multiplication
matrix_multiplication = np.dot(A2, B2.T)  # A2 * B2.T because shapes must match for matrix multiplication

# 3. Addition of both matrices
matrix_addition = A2 + B2

# 4. Subtraction of matrix B2 from A2
matrix_subtraction = A2 - B2

# 5. Division of matrix B2 by A2
matrix_division = B2 / A2

element_wise_multiplication, matrix_multiplication, matrix_addition, matrix_subtraction, matrix_division


(array([[  1,   4,   9,  16],
        [ 25,  36,  49,  64],
        [ 81, 100, 121, 144]]),
 array([[ 30,  70, 110],
        [ 70, 174, 278],
        [110, 278, 446]]),
 array([[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24]]),
 array([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]))

12. Which function in Numpy can be used to swap the byte order of an array?
The function np.ndarray.byteswap() can be used to swap the byte order of an array.

13. What is the significance of the np.linalg.inv function?
The np.linalg.inv function is used to compute the inverse of a matrix. The inverse is significant in solving systems of linear equations and in various matrix operations.

### 14. What does the np.reshape function do, and how is it used?

In [18]:

reshaped_array = np.reshape(array, (2, 6))
reshaped_array
print(reshaped_array.base)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


reshaped_array = np.reshape(array, (2, 6))

reshaped_array


15. What is broadcasting in Numpy?

Broadcasting is a mechanism that allows NumPy to perform element-wise operations on arrays of different shapes. It automatically expands the smaller array along the missing dimensions to match the shape of the larger array for the operation.